<?php
/**
 * Remove plugin-owned files and settings when Simple Redis Cache is deleted.
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

$simple_redis_cache_invalidate = static function ( string $path ): void {
	if ( function_exists( 'wp_opcache_invalidate' ) ) {
		wp_opcache_invalidate( $path, true );
	} elseif ( function_exists( 'opcache_invalidate' ) ) {
		@opcache_invalidate( $path, true );
	}
};

foreach ( array( WP_CONTENT_DIR . '/object-cache.php', WP_CONTENT_DIR . '/advanced-cache.php' ) as $simple_redis_cache_dropin ) {
	if ( ! is_readable( $simple_redis_cache_dropin ) ) {
		continue;
	}

	$simple_redis_cache_head = file_get_contents( $simple_redis_cache_dropin, false, null, 0, 16384 );
	if ( is_string( $simple_redis_cache_head ) && str_contains( $simple_redis_cache_head, 'Simple Redis Cache Drop-In' ) ) {
		@unlink( $simple_redis_cache_dropin );
		$simple_redis_cache_invalidate( $simple_redis_cache_dropin );
	}
}

$simple_redis_cache_config = WP_CONTENT_DIR . '/simple-redis-cache-config.php';
if ( is_readable( $simple_redis_cache_config ) ) {
	$simple_redis_cache_head = file_get_contents( $simple_redis_cache_config, false, null, 0, 512 );
	if ( is_string( $simple_redis_cache_head ) && str_contains( $simple_redis_cache_head, 'Generated by Simple Redis Cache' ) ) {
		@unlink( $simple_redis_cache_config );
		$simple_redis_cache_invalidate( $simple_redis_cache_config );
	}
}

delete_option( 'simple_redis_cache_settings' );
delete_option( '_simple_redis_cache_notices' );
delete_metadata( 'user', 0, '_simple_redis_cache_notices', '', true );
delete_site_transient( 'simple_redis_cache_github_update_data' );

unset(
	$simple_redis_cache_config,
	$simple_redis_cache_dropin,
	$simple_redis_cache_head,
	$simple_redis_cache_invalidate
);
